In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("C:/Users/kubas/Downloads/car.data", engine = "python", names = ['price', "maintenance", "doors", "persons", "trunk", "safety", "acceptance"])
df

      price maintenance  doors persons  trunk safety acceptance
0     vhigh       vhigh      2       2  small    low      unacc
1     vhigh       vhigh      2       2  small    med      unacc
2     vhigh       vhigh      2       2  small   high      unacc
3     vhigh       vhigh      2       2    med    low      unacc
4     vhigh       vhigh      2       2    med    med      unacc
...     ...         ...    ...     ...    ...    ...        ...
1723    low         low  5more    more    med    med       good
1724    low         low  5more    more    med   high      vgood
1725    low         low  5more    more    big    low      unacc
1726    low         low  5more    more    big    med       good
1727    low         low  5more    more    big   high      vgood

[1728 rows x 7 columns]

In [4]:
for i in range(len(df)):
    if df.price[i] == "vhigh":
        df.price[i] = 4
    elif df.price[i] == "high":
        df.price[i] = 3
    elif df.price[i] == "med":
        df.price[i] = 2
    elif df.price[i] == "low":
        df.price[i] = 1


    if df.maintenance[i] == "vhigh":
        df.maintenance[i] = 4
    elif df.maintenance[i] == "high":
        df.maintenance[i] = 3
    elif df.maintenance[i] == "med":
        df.maintenance[i] = 2
    elif df.maintenance[i] == "low":
        df.maintenance[i] = 1



    if df.doors[i] == "2":
        df.doors[i] = 1
    elif df.doors[i] == "3":
        df.doors[i] = 2
    elif df.doors[i] == "4":
        df.doors[i] = 3
    elif df.doors[i] == "5more":
        df.doors[i] = 4


    if df.persons[i] == "2":
        df.persons[i] = 1
    elif df.persons[i] == "4":
        df.persons[i] = 2
    elif df.persons[i] == "more":
        df.persons[i] = 3


    if df.trunk[i] == "small":
        df.trunk[i] = 1
    elif df.trunk[i] == "med":
        df.trunk[i] = 2
    elif df.trunk[i] == "big":
        df.trunk[i] = 3
    

    if df.safety[i] == "low":
        df.safety[i] = 1
    elif df.safety[i] == "med":
        df.safety[i] = 2
    elif df.safety[i] == "high":
        df.safety[i] = 3

In [5]:
df

     price maintenance doors persons trunk safety acceptance
0        4           4     1       1     1      1      unacc
1        4           4     1       1     1      2      unacc
2        4           4     1       1     1      3      unacc
3        4           4     1       1     2      1      unacc
4        4           4     1       1     2      2      unacc
...    ...         ...   ...     ...   ...    ...        ...
1723     1           1     4       3     2      2       good
1724     1           1     4       3     2      3      vgood
1725     1           1     4       3     3      1      unacc
1726     1           1     4       3     3      2       good
1727     1           1     4       3     3      3      vgood

[1728 rows x 7 columns]

In [6]:
from sklearn import neighbors, model_selection, metrics


features = ["price", "maintenance", "doors", "persons", "trunk", "safety"]

model = neighbors.KNeighborsClassifier(5)
xval = model_selection.KFold(10, shuffle = True)
scorer = metrics.make_scorer(metrics.cohen_kappa_score)
result = model_selection.cross_validate(model, df[features], df.acceptance, cv = xval, scoring = scorer, return_train_score = True)

In [7]:
print("Kappa Mean:", result["test_score"].mean())
print("Kappa SD:", result["test_score"].std())
print("Train Kappa Mean:", result["train_score"].mean())

Kappa Mean: 0.8403215543487168
Kappa SD: 0.034138944694385116
Train Kappa Mean: 0.9127169384371016

In [8]:
from sklearn import tree
model = tree.DecisionTreeClassifier(min_samples_leaf = 10)
xval = model_selection.KFold(5, shuffle = True)
scorer = metrics.make_scorer(metrics.cohen_kappa_score)
result = model_selection.cross_validate(model, df[features], df.acceptance, cv = xval, scoring = scorer, return_train_score = True)

In [9]:
print("Kappa Mean:", result["test_score"].mean())
print("Kappa SD:", result["test_score"].std())
print("Train Kappa Mean:", result["train_score"].mean())

Kappa Mean: 0.8658470968867686
Kappa SD: 0.03997319280217066
Train Kappa Mean: 0.9088636758942531

In [10]:
from sklearn import ensemble

model = ensemble.RandomForestClassifier(min_samples_leaf= 10)
xval = model_selection.StratifiedKFold(4, shuffle = True)
scorer = metrics.make_scorer(metrics.cohen_kappa_score)
result = model_selection.cross_validate(model, df[features], df.acceptance, cv = xval, scoring = scorer, return_train_score=True)

In [11]:
print("Kappa Mean: ", result["test_score"].mean())
print("Kappa SD: ", result["test_score"].std())
print("Train Kappa Mean: ", result["train_score"].mean())

Kappa Mean:  0.8680321236092329
Kappa SD:  0.007418588049671126
Train Kappa Mean:  0.9063744851787396

In [12]:
from sklearn import model_selection
model = ensemble.RandomForestClassifier(min_samples_leaf=5)
not_price_features = []
for feature in features:
    if feature != "price":
        not_price_features.append(feature)



xval = model_selection.KFold(10, shuffle = True)
scorer = metrics.make_scorer(metrics.cohen_kappa_score)
result = model_selection.cross_validate(model, df[not_price_features], df.acceptance, cv = xval, scoring = scorer, return_train_score=True)
print("Kappa:", result["test_score"].mean())
print("Kappa SD:", result["test_score"].std())
print("Train Kappa:", result["train_score"].mean())

Kappa: 0.49417091238382815
Kappa SD: 0.08704222766823115
Train Kappa: 0.6368183006521433

In [13]:
not_safety_features = []
for feature in features:
    if feature != "safety":
        not_safety_features.append(feature)


xval = model_selection.KFold(10, shuffle = True)
scorer = metrics.make_scorer(metrics.cohen_kappa_score)
result = model_selection.cross_validate(model, df[not_safety_features], df.acceptance, cv = xval, scoring = scorer, return_train_score=True)
print("Kappa:", result["test_score"].mean())
print("Kappa SD:", result["test_score"].std())
print("Train Kappa:", result["train_score"].mean())

Kappa: 0.31883120511376956
Kappa SD: 0.06843160843241337
Train Kappa: 0.48409207001530064

In [14]:
not_doors_features = []
for feature in features:
    if feature != "doors":
        not_doors_features.append(feature)


xval = model_selection.KFold(10, shuffle = True)
scorer = metrics.make_scorer(metrics.cohen_kappa_score)
result = model_selection.cross_validate(model, df[not_doors_features], df.acceptance, cv = xval, scoring = scorer, return_train_score=True)
print("Kappa:", result["test_score"].mean())
print("Kappa SD:", result["test_score"].std())
print("Train Kappa:", result["train_score"].mean())

Kappa: 0.8963042899365018
Kappa SD: 0.021397952487332297
Train Kappa: 0.9184277266090831

In [15]:
model.fit(df[features], df.acceptance)
importances = pd.Series(model.feature_importances_, index = features)
importances.sort_values(ascending = False)

safety         0.338957
persons        0.282253
price          0.155813
maintenance    0.126005
trunk          0.068247
doors          0.028724
dtype: float64

In [16]:
not_doors_features = []
for feature in features:
    if feature != "doors":
        not_doors_features.append(feature)

not_doorsortrunk_features = []
for feature in not_doors_features:
    if feature != "trunk":
        not_doorsortrunk_features.append(feature)


xval = model_selection.KFold(10, shuffle = True)
scorer = metrics.make_scorer(metrics.cohen_kappa_score)
result = model_selection.cross_validate(model, df[not_doors_features], df.acceptance, cv = xval, scoring = scorer, return_train_score=True)
print("Kappa:", result["test_score"].mean())
print("Kappa SD:", result["test_score"].std())
print("Train Kappa:", result["train_score"].mean())

Kappa: 0.9067990748634047
Kappa SD: 0.022676968835997697
Train Kappa: 0.9179561506237176

In [18]:
only_highsafety_highpersons_df = df[(df.safety == 3) & (df.persons == 3) & (df.price == 1)]
only_highsafety_highpersons_df

     price maintenance doors persons trunk safety acceptance
1316     1           4     1       3     1      3      unacc
1319     1           4     1       3     2      3        acc
1322     1           4     1       3     3      3        acc
1343     1           4     2       3     1      3        acc
1346     1           4     2       3     2      3        acc
1349     1           4     2       3     3      3        acc
1370     1           4     3       3     1      3        acc
1373     1           4     3       3     2      3        acc
1376     1           4     3       3     3      3        acc
1397     1           4     4       3     1      3        acc
1400     1           4     4       3     2      3        acc
1403     1           4     4       3     3      3        acc
1424     1           3     1       3     1      3      unacc
1427     1           3     1       3     2      3        acc
1430     1           3     1       3     3      3      vgood
1451     1           3     2       3     1      3        acc
1454     1           3     2       3     2      3      vgood
1457     1           3     2       3     3      3      vgood
1478     1           3     3       3     1      3        acc
1481     1           3     3       3     2      3      vgood
1484     1           3     3       3     3      3      vgood
1505     1           3     4       3     1      3        acc
1508     1           3     4       3     2      3      vgood
1511     1           3     4       3     3      3      vgood
1532     1           2     1       3     1      3      unacc
1535     1           2     1       3     2      3       good
1538     1           2     1       3     3      3      vgood
1559     1           2     2       3     1      3       good
1562     1           2     2       3     2      3      vgood
1565     1           2     2       3     3      3      vgood
1586     1           2     3       3     1      3       good
1589     1           2     3       3     2      3      vgood
1592     1           2     3       3     3      3      vgood
1613     1           2     4       3     1      3       good
1616     1           2     4       3     2      3      vgood
1619     1           2     4       3     3      3      vgood
1640     1           1     1       3     1      3      unacc
1643     1           1     1       3     2      3       good
1646     1           1     1       3     3      3      vgood
1667     1           1     2       3     1      3       good
1670     1           1     2       3     2      3      vgood
1673     1           1     2       3     3      3      vgood
1694     1           1     3       3     1      3       good
1697     1           1     3       3     2      3      vgood
1700     1           1     3       3     3      3      vgood
1721     1           1     4       3     1      3       good
1724     1           1     4       3     2      3      vgood
1727     1           1     4       3     3      3      vgood